name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install alsa
      run: sudo apt-get install -y alsa-base alsa-utils libasound2-dev && sudo apt install librust-alsa-sys-dev && pkg-config --libs --cflags alsa
    - name: Install libudev
      run: sudo apt install librust-libudev-dev && pkg-config --libs --cflags libudev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

